{{ if .Values.traefikIngress.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  labels:
    app: traefik
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - --api.insecure # TODO: fix to secure
            - --providers.kubernetesingress
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
{{ end }}
---
{{ if .Values.traefikIngress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
{{ end }}
---
{{ if .Values.traefikIngress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.traefikIngress.traefikIP }}
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik
{{ end }}