{{ if .Values.traefikIngress.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-account
  namespace: default
{{ end }}
---
{{ if .Values.traefikIngress.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-role
subjects:
  - kind: ServiceAccount
    name: traefik-account
    namespace: default # Using "default" because we did not specify a namespace when creating the ClusterAccount.
{{ end }}