apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-microservices.fullname" . }}-auth-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-auth-server
    {{- include "hello-microservices.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.APIServer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-auth-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-auth-server
        {{- include "hello-microservices.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.backend.AuthServer.serviceAccountName }}
      containers:
        - name: auth-server
          image: {{ .Values.backend.AuthServer.image.repository }}:{{ .Values.backend.AuthServer.image.tag }}
          imagePullPolicy: {{ .Values.backend.AuthServer.image.pullPolicy }}
          ports:
            {{- toYaml .Values.backend.AuthServer.ports | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.AuthServer.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.backend.AuthServer.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /status
              port: http
            {{- toYaml .Values.backend.AuthServer.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /status
              port: http
            {{- toYaml .Values.backend.AuthServer.readinessProbe | nindent 12 }}
          env:
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "hello-microservices.secretname" . }}
                  key: POSTGRES_DB_PASSWORD
            - name: POSTGRES_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "hello-microservices.secretname" . }}
                  key: POSTGRES_DB_USERNAME
            - name: POSTGRES_DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hello-microservices.configname" . }}
                  key: POSTGRES_DB_SERVER
            - name: POSTGRES_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hello-microservices.configname" . }}
                  key: POSTGRES_DB_PORT