apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-microservices.fullname" . }}-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-admin-secret
data:
  DB_USER: {{ .Values.adminConfig.MONGO_DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.adminConfig.MONGO_DB_PASSWORD | b64enc | quote }}
  JWT_SECRET: {{ .Values.adminConfig.JWTSecret | b64enc | quote }}
  POSTGRES_DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_DB_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}