apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-microservices.fullname" . }}-auth-server-service
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-api-server
spec:
  type: {{ .Values.backend.AuthServer.service.type }}
  ports:
    - name: auth-server
      port: {{ .Values.backend.AuthServer.service.apiHTTPServer.port }}
      targetPort: {{ .Values.backend.AuthServer.service.apiHTTPServer.targetPort }}
  selector:
    app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-auth-server