apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-microservices.fullname" . }}-admin-config
  namespace: {{ .Release.Namespace }}
data:
  DB_SERVER: "mongodb://mongo-service:27017"
  AGENT_SCOPE: cluster
  AGENT_NAMESPACE: litmus
  VERSION: "3.0.0-beta7"
  SKIP_SSL_VERIFY: "false"
  # Configurations if you are using dex for OAuth
  DEX_ENABLED: "false"
  OIDC_ISSUER: "http://<Your Domain>:32000"
  DEX_OAUTH_CALLBACK_URL: "http://<litmus-portal frontend exposed URL>:8080/auth/dex/callback"
  DEX_OAUTH_CLIENT_ID: "LitmusPortalAuthBackend"
  DEX_OAUTH_CLIENT_SECRET: "ZXhhbXBsZS1hcHAtc2VjcmV0"
  OAuthJwtSecret: "litmus-oauth@123"