apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-microservices.fullname" . }}-frontend-service
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-frontend
    {{- include "hello-microservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-frontend