apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-microservices.fullname" . }}-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-admin-secret
data:
  DB_USER: {{ .Values.adminConfig.DBUSER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.adminConfig.DBPASSWORD | b64enc | quote }}
  JWT_SECRET: {{ .Values.adminConfig.JWTSecret | b64enc | quote }}