apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.APIServer.serviceAccountName }}
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hello-microservices.name" . }}-api-server