opentelemetry-collector:
  enabled: true
  nameOverride: otelcol
  mode: deployment
  resources:
    limits:
      memory: 125Mi
  service:
    type: ClusterIP
  ports:
    metrics:
      enabled: true
    prometheus:
      enabled: true
      containerPort: 9464
      servicePort: 9464
      protocol: TCP
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9464"
  config:
    receivers:
      otlp:
        protocols:
          http:
            # Bind to 0.0.0.0 to allow for `kubectl port-forward` to work
            # This may be susceptible to denial of service attacks - CWE-1327 https://cwe.mitre.org/data/definitions/1327.html
            endpoint: 0.0.0.0:4318
            # Since this collector needs to receive data from the web, enable cors for all origins
            # `allowed_origins` can be refined for your deployment domain
            cors:
              allowed_origins:
                - "http://*"
                - "https://*"
jaeger:
  enabled: true
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
    args:
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - 'http://observability-prometheus-server:9090'
    extraEnv:
      - name: METRICS_STORAGE_TYPE
        value: prometheus
    resources:
      limits:
        memory: 300Mi
  storage:
    type: none
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

prometheus:
  enabled: true
  alertmanager:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false

grafana:
  enabled: false
#  grafana.ini:
#    auth:
#      disable_login_form: true
#    auth.anonymous:
#      enabled: true
#      org_name: Main Org.
#      org_role: Admin
#    server:
#      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
#      serve_from_sub_path: true
#  adminPassword: admin
#  datasources:
#    datasources.yaml:
#      apiVersion: 1
#      datasources:
#        - name: Prometheus
#          uid: webstore-metrics
#          type: prometheus
#          url: 'http://{{ include "otel-demo.name" . }}-prometheus-server:9090'
#          editable: true
#          isDefault: true
#          jsonData:
#            exemplarTraceIdDestinations:
#              - datasourceUid: webstore-traces
#                name: trace_id
#              - url: http://localhost:8080/jaeger/ui/trace/$${__value.raw}
#                name: trace_id
#                urlDisplayLabel: View in Jaeger UI
#
#        - name: Jaeger
#          uid: webstore-traces
#          type: jaeger
#          url: 'http://{{ include "otel-demo.name" . }}-jaeger-query:16686/jaeger/ui'
#          editable: true
#          isDefault: false
#  dashboardProviders:
#    dashboardproviders.yaml:
#      apiVersion: 1
#      providers:
#        - name: 'default'
#          orgId: 1
#          folder: ''
#          type: file
#          disableDeletion: false
#          editable: true
#          options:
#            path: /var/lib/grafana/dashboards/default
#  dashboardsConfigMaps:
#    default: '{{ include "otel-demo.name" . }}-grafana-dashboards'
#  resources:
#    limits:
#      memory: 100Mi