apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.{{ .Values.adminConfig.DOMAIN_NAME }}`)
      priority: 10
      services:
        - name: argocd-server
          port: 443
    - kind: Rule
      match: Host(`argocd.{{ .Values.adminConfig.DOMAIN_NAME }}`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 443
          scheme: h2c
  tls:
    secretName: argocd.{{ .Values.adminConfig.DOMAIN_NAME }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd.{{ .Values.adminConfig.DOMAIN_NAME }}
spec:
  dnsNames:
    - argocd.{{ .Values.adminConfig.DOMAIN_NAME }}
  secretName: argocd.{{ .Values.adminConfig.DOMAIN_NAME }}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer